### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Crazily** [EmeraldSnorlax/DiscordRPC-PC-Stats#1]
The configuration is not saved. Meaning every time the application is launched you must fill out the questions again. Another thing, The clock speed that the cpu is running at isn't really an accurate determination of cpu usage. Other than that, It's flawless and works as intended.

**Comment by EmeraldSnorlax** [comment]
I'll look into saving the configuration, and getting true usage should be a quick fix too
Thanks for the feedback

**Comment by Crazily** [comment]
Downloading and testing the latest commit. Excited to see if this is good

**Comment by EmeraldSnorlax** [comment]
I just released a build of it as binaries in releases

**Comment by Crazily** [comment]
Alrighty

**Comment by EmeraldSnorlax** [comment]
Closing issue, both features have been now added

**Comment by Crazily** [comment]
Works perfectly.
